---

version: "3.7"

services:
  sftp:
    container_name: sftp
    image: atmoz/sftp:${SFTP_VERSION_TAG}
    volumes:
      - ./ssh-keys/dummy-key.pub:/home/${EXEC_USER}/.ssh/keys/dummy-key.pub:ro
      - ./chown.sh:/etc/sftp.d/chown.sh:ro
      - sftp-vol:/home/${EXEC_USER}/upload
    ports:
      - "2222:22"
    environment:
      - EXEC_USER=${EXEC_USER}
    command: ${EXEC_USER}::::upload

volumes:
  sftp-vol:
    name: sftp-vol
    driver: local
